default_platform(:android)

platform :android do
  desc "Build AAB and upload to Google Play internal track"
  lane :internal do
    version_name = ENV["CI_VERSION_NAME"]
    version_code = ENV["CI_VERSION_CODE"]

    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "VERSION_NAME" => version_name,
        "VERSION_CODE" => version_code
      }
    )

    aab_path = lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH] || lane_context[SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS]&.first

    UI.user_error!("AAB 경로를 찾지 못했어요. GRADLE_*_AAB_OUTPUT_PATHS 확인 필요") unless aab_path

    # ✅ Play 업로드
    upload_to_play_store(
      package_name: "com.dasii",
      track: "internal",
      aab: aab_path,
      json_key_data: ENV["SUPPLY_JSON_KEY_DATA"],
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
